-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Nedbrydning"
(
    nedbrydning_id bigserial,
    nedbrydningstid bigint,
    PRIMARY KEY (nedbrydning_id)
);

CREATE TABLE IF NOT EXISTS public."Skrald"
(
    "Skrald_id" bigserial,
    navn character varying(50) COLLATE pg_catalog."default",
    skralde_kat_id bigint,
    nedbrydning_id bigint,
    farligfaktor_id bigint,
    CONSTRAINT "Skrald_pkey" PRIMARY KEY ("Skrald_id")
);

CREATE TABLE IF NOT EXISTS public.skraldekategori
(
    skralde_kat_id bigserial,
    fraktion character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT skraldekategori_pkey PRIMARY KEY (skralde_kat_id)
);

CREATE TABLE IF NOT EXISTS public."Falighedsfaktor"
(
    farligfaktor_id bigserial,
    "Farlighedsniveau" character varying(40),
    "Beskrivelse" character varying(250),
    PRIMARY KEY (farligfaktor_id)
);

ALTER TABLE IF EXISTS public."Skrald"
    ADD FOREIGN KEY (farligfaktor_id)
    REFERENCES public."Falighedsfaktor" (farligfaktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Skrald"
    ADD FOREIGN KEY (nedbrydning_id)
    REFERENCES public."Nedbrydning" (nedbrydning_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Skrald"
    ADD FOREIGN KEY (skralde_kat_id)
    REFERENCES public.skraldekategori (skralde_kat_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;