
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Farlighedsfaktor"
(
    farligfaktor_id bigint NOT NULL DEFAULT nextval('"Falighedsfaktor_farligfaktor_id_seq"'::regclass),
    "Farlighedsniveau" character varying(40) COLLATE pg_catalog."default",
    "Beskrivelse" character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT "Falighedsfaktor_pkey" PRIMARY KEY (farligfaktor_id)
);

CREATE TABLE IF NOT EXISTS public.skrald
(
    skrald_id bigint NOT NULL DEFAULT nextval('"Skrald_Skrald_id_seq"'::regclass),
    navn character varying(50) COLLATE pg_catalog."default",
    skralde_kat_id bigint,
    farligfaktor_id bigint,
    nedbrydningstid character varying(40) COLLATE pg_catalog."default",
    "nedbrydningstidværdi" bigint,
    beskrivelse character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT "Skrald_pkey" PRIMARY KEY (skrald_id)
);

CREATE TABLE IF NOT EXISTS public.skraldekategori
(
    skralde_kat_id bigint NOT NULL DEFAULT nextval('skraldekategori_skralde_kat_id_seq'::regclass),
    fraktion character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT skraldekategori_pkey PRIMARY KEY (skralde_kat_id)
);

ALTER TABLE IF EXISTS public.skrald
    ADD CONSTRAINT "Skrald_farligfaktor_id_fkey" FOREIGN KEY (farligfaktor_id)
    REFERENCES public."Farlighedsfaktor" (farligfaktor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.skrald
    ADD CONSTRAINT "Skrald_skralde_kat_id_fkey" FOREIGN KEY (skralde_kat_id)
    REFERENCES public.skraldekategori (skralde_kat_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;