INSERT INTO skrald (beskrivelse)
VALUES ('Cigaretfilteret er lavet af plasttypen plastcelluloseacetat, en ikke-biologisk nedbrydelig plast, der bliver til mikroplast.'),
('Nicotinposer består af tobak, papir og små mængder plastik'),
('Tyggegummi består af syntetisk gummi, der er tilsat sødestoffer, blødgørere og smagsstoffer, og deler egenskaber med andre gummibaserede produkter som bildæk og lim.'),
('En papirpose består af organisk materiale og er vandopløselig.'),
('Plastik poser er ikke biologisk nedbrydelige. I stedet nedbrydes plastposen over tid til mindre og mindre plastpartikler'),
('Hundelort er orgarnisk materiale og er nedbrydeligt'),
('Aluminiomsdåser består af metal som har en lang nedbrydelsestid'),
('Plastik flasker er ikke biologisk nedbrydelige. I stedet nedbrydes plastposen over tid til mindre og mindre plastpartikler'),
('Glas er et holdbart materiale'),
('Ballonner er lavet af en forarbejdet form for latex'),
('Æbleskrog er organsik materiale'),
('Fiskesnøre er lavet af flere forskellige materialer blandt andet plastik og nylon.'),
('Plastkrus er ikke biologisk nedbrydelige. I stedet nedbrydes plastposen over tid til mindre og mindre plastpartikler'),
('Ispinde behandles med en fødevaregodkendt voks, der gør, at isen ikke går i forbindelse med træet'),
('Indersiden af papkruset er dækket med et tyndt lag plast af typen polyethylen, som er en form for mikroplast.'),
('En kapsel er lavet af metal med en tætningsplade bestående af en plastikskive'),
('Appelsisnskrald er orgarnsik materiale'),
('Banankrald er orgarnsik materiale'),
('En mælkekarton har et lag af plastik selvom resten er karton'),
('Nylon er en syntetisk polymer, der er sammensat af flere enheder, nemlig en diamin og en dicarboxylsyre ved hjælp af amidbindinger'),
('En mobiltelefon indeholder 40 forskellige materialer'),
('En cykel er lavet af enten carbon eller aluminium'),
('Møbler består af forskellige former for træ som er forarbejdet'),
('Tøj er lavet af naturfibre som hør, silke og bomuld, derudover kunstfibre som akryl, nylon, polyester og spandex')
